---
language: node_js
node_js:
  - "6"

sudo: false

addons:
  firefox: "50.0"

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

env:
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-2.0.3
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-2.11.x
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=fastboot

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install -g yarn
  - yarn --version
  - bower --version

install:
  - yarn install
  - npm rebuild node-sass
  - bower install

before_script:
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
